### ISSUE TITLE
Margin to Content

### ISSUE THREAD

**Issue by erikperin** [SPQRInc/pagekit-shariff#1]
It would be great if there were an upper margin of the buttons for the content.

**Comment by ahoiroman** [comment]
I will include this possibility in the next version. In the meantime you can add custom CSS to your site's settings to archive this.

**Comment by erikperin** [comment]
Ok... this extension are job... thank you... :)

I put this in my site and works great....

`.shariff{
padding-top:30px;
}`

**Comment by ahoiroman** [comment]
Alrigh :) Nice to hear that it's working fine.
